/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        /** Update Job */
        put: operations["update_job_jobs__job_id__put"];
        post?: never;
        /**
         * Close Job
         * @description Soft-delete: sets status='closed'. Never a real SQL DELETE — avoids FK errors
         *     against candidates/interviews/audit_log and preserves audit history.
         */
        delete: operations["close_job_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/competencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Competencies */
        get: operations["get_job_competencies_jobs__job_id__competencies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Candidate
         * @description HR/seed-side only for MVP — not a public candidate-facing endpoint (see Area 1 T8 note).
         */
        post: operations["create_candidate_candidates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{candidate_id}/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite Candidate
         * @description Generates a fresh, meaningful invite token — only callable once the job's
         *     interview questions are approved (T9b). Regenerates the placeholder token set at
         *     CV-upload time (T5), which was never meant as a real invite link.
         */
        post: operations["invite_candidate_candidates__candidate_id__invite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{candidate_id}/self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Candidate Self
         * @description Token-authenticated candidate self-info. A 401 here (invalid/expired token) is what
         *     Area 1 T3's frontend route guard renders as the shared 'link tidak valid / sudah
         *     kadaluarsa' screen.
         */
        get: operations["get_candidate_self_candidates__candidate_id__self_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{candidate_id}/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Consent
         * @description Token-authenticated. Records PDP consent before the candidate can start the
         *     interview (Area 1 T8 gate; enforced server-side already via services.consent in the
         *     interview-answer submit path).
         */
        post: operations["submit_consent_candidates__candidate_id__consent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ranked Candidates */
        get: operations["get_ranked_candidates_jobs__job_id__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/questions/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Job Questions
         * @description Generates 2-3 draft questions from the JD via Flash. Replaces any existing draft questions.
         */
        post: operations["generate_job_questions_jobs__job_id__questions_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Job Questions */
        get: operations["list_job_questions_jobs__job_id__questions_get"];
        /**
         * Update Job Questions
         * @description HR edits/adds/removes draft questions. Only draft-status questions can be edited.
         */
        put: operations["update_job_questions_jobs__job_id__questions_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/questions/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Job Questions
         * @description Flips all draft questions to approved. Candidates only ever see approved questions.
         */
        post: operations["approve_job_questions_jobs__job_id__questions_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{candidate_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Candidate Questions
         * @description Candidate-facing (token-authenticated). Only ever returns approved questions —
         *     candidates never see drafts.
         */
        get: operations["list_candidate_questions_candidates__candidate_id__questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{candidate_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Interview Answer
         * @description Candidate-facing (token-authenticated, not HR JWT). Consent-gated: 403 without a
         *     consent_records row for this candidate.
         */
        post: operations["submit_interview_answer_candidates__candidate_id__answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{candidate_id}/answers/{answer_id}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Score Candidate Answer */
        post: operations["score_candidate_answer_candidates__candidate_id__answers__answer_id__score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{candidate_id}/interview-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Interview Summary */
        post: operations["build_interview_summary_candidates__candidate_id__interview_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Decision
         * @description Records HR's final pass/reject decision. No code path anywhere finalizes a
         *     candidate without this endpoint being explicitly called by a human — there is no
         *     automatic-decision helper, scheduled job, or scoring threshold that writes here.
         */
        post: operations["record_decision_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{candidate_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Candidate Report */
        get: operations["get_candidate_report_candidates__candidate_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{candidate_id}/send-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Candidate Report
         * @description HR triggers delivery with one click — PDF + summary auto-sent via Telegram.
         */
        post: operations["send_candidate_report_candidates__candidate_id__send_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerOut */
        AnswerOut: {
            /** Answer Id */
            answer_id: number;
            /** Audio Path */
            audio_path: string;
            /** Transcript Text */
            transcript_text: string;
        };
        /** Body_create_candidate_candidates_post */
        Body_create_candidate_candidates_post: {
            /** Job Id */
            job_id: number;
            /** Alias */
            alias: string;
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_submit_interview_answer_candidates__candidate_id__answers_post */
        Body_submit_interview_answer_candidates__candidate_id__answers_post: {
            /** Question Id */
            question_id: number;
            /** Session */
            session: string;
            /** Token */
            token: string;
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** CandidateOut */
        CandidateOut: {
            /** Id */
            id: number;
            /** Job Id */
            job_id: number;
            /** Alias */
            alias: string;
        };
        /** CandidateQuestionOut */
        CandidateQuestionOut: {
            /** Id */
            id: number;
            /** Question Text */
            question_text: string;
            /** Order Index */
            order_index: number;
        };
        /**
         * CandidateSelfOut
         * @description Candidate-facing self-info, resolved by token — powers Area 1 T3's route guards
         *     (expired/invalid token, consent-required redirect) without exposing HR-only fields.
         */
        CandidateSelfOut: {
            /** Id */
            id: number;
            /** Job Title */
            job_title: string;
            /** Has Consent */
            has_consent: boolean;
            /** Has Telegram Link */
            has_telegram_link: boolean;
            /** Interview Completed */
            interview_completed: boolean;
        };
        /** CompetencyOut */
        CompetencyOut: {
            /** Id */
            id: number;
            /** Competency Name */
            competency_name: string;
            /** Importance Level */
            importance_level: number;
        };
        /** ConsentOut */
        ConsentOut: {
            /** Candidate Id */
            candidate_id: number;
            /** Consent Given */
            consent_given: boolean;
        };
        /** ConsentRequest */
        ConsentRequest: {
            /** Token */
            token: string;
            /** Consent Text Version */
            consent_text_version: string;
        };
        /** DecisionOut */
        DecisionOut: {
            /** Id */
            id: number;
            /** Candidate Id */
            candidate_id: number;
            /** Decision */
            decision: string;
            /** Decided By */
            decided_by: number;
        };
        /** DecisionRequest */
        DecisionRequest: {
            /** Candidate Id */
            candidate_id: number;
            /** Decision */
            decision: string;
            /** Notes */
            notes?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InterviewSummaryOut */
        InterviewSummaryOut: {
            /** Overall Score */
            overall_score: number;
            /** Ai Summary Text */
            ai_summary_text: string;
        };
        /** InviteOut */
        InviteOut: {
            /** Candidate Id */
            candidate_id: number;
            /** Token */
            token: string;
            /** Token Expires At */
            token_expires_at: string;
        };
        /** JobCreateRequest */
        JobCreateRequest: {
            /** Title */
            title: string;
            /** Responsibilities */
            responsibilities: string;
            /** Requirements */
            requirements: string;
            /** Qualifications */
            qualifications: string;
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: number;
            /** Company Id */
            company_id: number;
            /** Title */
            title: string;
            /** Responsibilities */
            responsibilities: string;
            /** Requirements */
            requirements: string;
            /** Qualifications */
            qualifications: string;
            /** Status */
            status: string;
        };
        /** JobUpdateRequest */
        JobUpdateRequest: {
            /** Title */
            title: string;
            /** Responsibilities */
            responsibilities: string;
            /** Requirements */
            requirements: string;
            /** Qualifications */
            qualifications: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** MatchOut */
        MatchOut: {
            /** Candidate Id */
            candidate_id: number;
            /** Alias */
            alias: string;
            /** Overall Score */
            overall_score: number;
            /** Rank */
            rank: number;
            /** Competency Breakdown */
            competency_breakdown: Record<string, never>;
        };
        /** QuestionOut */
        QuestionOut: {
            /** Id */
            id: number;
            /** Job Id */
            job_id: number;
            /** Question Text */
            question_text: string;
            /** Order Index */
            order_index: number;
            /** Status */
            status: string;
        };
        /** QuestionUpdateItem */
        QuestionUpdateItem: {
            /** Id */
            id?: number | null;
            /** Question Text */
            question_text: string;
            /** Order Index */
            order_index: number;
        };
        /** QuestionsUpdateRequest */
        QuestionsUpdateRequest: {
            /** Questions */
            questions: components["schemas"]["QuestionUpdateItem"][];
        };
        /** ScoreOut */
        ScoreOut: {
            /** Clarity */
            clarity: number;
            /** Relevance */
            relevance: number;
            /** Technical Depth */
            technical_depth: number;
            /** Summary */
            summary: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_jobs_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_jobs__job_id__put: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_job_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_competencies_jobs__job_id__competencies_get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetencyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_candidate_candidates_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_candidate_candidates_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_candidate_candidates__candidate_id__invite_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                candidate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_candidate_self_candidates__candidate_id__self_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path: {
                candidate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateSelfOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_consent_candidates__candidate_id__consent_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ranked_candidates_jobs__job_id__candidates_get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_job_questions_jobs__job_id__questions_generate_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_job_questions_jobs__job_id__questions_get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_questions_jobs__job_id__questions_put: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionsUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_job_questions_jobs__job_id__questions_approve_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_candidate_questions_candidates__candidate_id__questions_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path: {
                candidate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateQuestionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_interview_answer_candidates__candidate_id__answers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_submit_interview_answer_candidates__candidate_id__answers_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_candidate_answer_candidates__candidate_id__answers__answer_id__score_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                candidate_id: number;
                answer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_interview_summary_candidates__candidate_id__interview_summary_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                candidate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_decision_decisions_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_candidate_report_candidates__candidate_id__report_get: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                candidate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_candidate_report_candidates__candidate_id__send_report_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path: {
                candidate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
